import type { CountryProfile, Range } from "./types";

const r = (min: number, max: number): Range => ({ min, max });

/**
 * Figures are EUR/year unless stated, converted at rough mid-2025 rates for
 * non-euro countries, and describe PUBLIC institutions. Private schools and
 * medicine/MBA programmes sit far above these bands.
 *
 * `lastReviewed` is load-bearing: anything older than ~12 months should be
 * re-checked against the ministry/immigration source before you rely on it.
 */
const REVIEWED = "2025-06-01";

function def(p: Omit<CountryProfile, "lastReviewed"> & { lastReviewed?: string }): CountryProfile {
  return { lastReviewed: REVIEWED, ...p };
}

export const COUNTRY_PROFILES: CountryProfile[] = [
  def({
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["German"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(0, 3000),
    semesterFee: r(100, 400),
    livingCostPerMonth: r(900, 1300),
    proofOfFundsPerYear: 11904,
    healthInsurancePerMonth: 125,
    englishMasters: "extensive",
    postStudyWorkMonths: 18,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Aufenthaltserlaubnis §16b",
    notes:
      "Tuition-free at public universities for all nationalities except Baden-Württemberg (~€1,500/semester for non-EU). Blocked account (Sperrkonto) required for the visa. 18-month job-seeking permit after graduation; EU Blue Card can cut permanent residence to 21–33 months.",
  }),
  def({
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["German"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(1454, 1454),
    semesterFee: r(50, 60),
    livingCostPerMonth: r(950, 1400),
    proofOfFundsPerYear: 16374,
    healthInsurancePerMonth: 70,
    englishMasters: "moderate",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Aufenthaltsbewilligung Student",
    notes:
      "Non-EU pay €726.72/semester at public universities; EU students pay only the ÖH student union fee if they finish within the standard duration. Proof of funds is age-banded (higher if you are 24+).",
  }),
  def({
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    eu: false,
    schengen: true,
    currency: "CHF",
    languages: ["German", "French", "Italian"],
    tuitionEu: r(1000, 2000),
    tuitionNonEu: r(1000, 4500),
    semesterFee: r(50, 150),
    livingCostPerMonth: r(1600, 2500),
    proofOfFundsPerYear: 22000,
    healthInsurancePerMonth: 120,
    englishMasters: "extensive",
    postStudyWorkMonths: 6,
    workHoursPerWeek: 15,
    permanentResidenceYears: 10,
    studentVisaName: "Permit B (student)",
    notes:
      "Very low tuition (ETH/EPFL ~CHF 1,300/year) offset by the highest living costs in Europe. Non-EU work permits after graduation are quota-limited; permanent residence typically takes 10 years.",
  }),
  def({
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Dutch"],
    tuitionEu: r(2530, 2601),
    tuitionNonEu: r(8000, 22000),
    semesterFee: null,
    livingCostPerMonth: r(900, 1500),
    proofOfFundsPerYear: 14000,
    healthInsurancePerMonth: 130,
    englishMasters: "extensive",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 16,
    permanentResidenceYears: 5,
    studentVisaName: "MVV + VVR study residence permit",
    notes:
      "Statutory fee for EU nationals, institutional fee for non-EU. The zoekjaar (orientation year) gives 12 months of unrestricted work rights after graduation. Housing shortage is the real constraint, not admission.",
  }),
  def({
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Dutch", "French", "German"],
    tuitionEu: r(950, 1100),
    tuitionNonEu: r(2000, 6000),
    semesterFee: null,
    livingCostPerMonth: r(850, 1250),
    proofOfFundsPerYear: 9600,
    healthInsurancePerMonth: 60,
    englishMasters: "moderate",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Type D student visa",
    notes:
      "Flemish and French communities set fees separately. Non-EU pay an increased 'inscription' fee that varies widely by institution.",
  }),
  def({
    code: "FR",
    name: "France",
    flag: "🇫🇷",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["French"],
    tuitionEu: r(175, 400),
    tuitionNonEu: r(250, 3770),
    semesterFee: r(100, 105),
    livingCostPerMonth: r(800, 1400),
    proofOfFundsPerYear: 7380,
    healthInsurancePerMonth: 25,
    englishMasters: "moderate",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "VLS-TS étudiant",
    notes:
      "Differentiated fees for non-EU (€2,770 bachelor / €3,770 master) but a large share of universities waive them down to the EU rate. Grandes écoles price separately. CAF housing aid is available to international students.",
  }),
  def({
    code: "IT",
    name: "Italy",
    flag: "🇮🇹",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Italian"],
    tuitionEu: r(0, 4000),
    tuitionNonEu: r(0, 4000),
    semesterFee: null,
    livingCostPerMonth: r(750, 1250),
    proofOfFundsPerYear: 6600,
    healthInsurancePerMonth: 12,
    englishMasters: "moderate",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Visto per studio (type D)",
    notes:
      "Fees are income-scaled via the ISEE declaration and apply equally to non-EU students, so low-income applicants often pay near zero. Regional DSU grants cover housing and meals for many.",
  }),
  def({
    code: "ES",
    name: "Spain",
    flag: "🇪🇸",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Spanish"],
    tuitionEu: r(700, 2500),
    tuitionNonEu: r(700, 4000),
    semesterFee: null,
    livingCostPerMonth: r(700, 1250),
    proofOfFundsPerYear: 7800,
    healthInsurancePerMonth: 60,
    englishMasters: "limited",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 30,
    permanentResidenceYears: 5,
    studentVisaName: "Estancia por estudios",
    notes:
      "Public fees are set per credit by each autonomous community; Catalonia and Madrid are the most expensive. Student time now counts fully toward residence, and post-study job-search is 12 months.",
  }),
  def({
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Portuguese"],
    tuitionEu: r(697, 1250),
    tuitionNonEu: r(3000, 8000),
    semesterFee: null,
    livingCostPerMonth: r(650, 1050),
    proofOfFundsPerYear: 9840,
    healthInsurancePerMonth: 40,
    englishMasters: "moderate",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Visto de residência D4",
    notes:
      "'Estudante internacional' status carries a separate, much higher fee set by each institution. Living costs are among the lowest in Western Europe.",
  }),
  def({
    code: "SE",
    name: "Sweden",
    flag: "🇸🇪",
    eu: true,
    schengen: true,
    currency: "SEK",
    languages: ["Swedish"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(7000, 16000),
    semesterFee: r(30, 35),
    livingCostPerMonth: r(850, 1300),
    proofOfFundsPerYear: 11500,
    healthInsurancePerMonth: 0,
    englishMasters: "extensive",
    postStudyWorkMonths: 12,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Residence permit for studies",
    notes:
      "Free for EU/EEA, SEK 80,000–190,000/year for everyone else, though university and Swedish Institute scholarships are substantial. No formal cap on working hours during study.",
  }),
  def({
    code: "NO",
    name: "Norway",
    flag: "🇳🇴",
    eu: false,
    schengen: true,
    currency: "NOK",
    languages: ["Norwegian"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(11000, 40000),
    semesterFee: r(60, 80),
    livingCostPerMonth: r(1050, 1600),
    proofOfFundsPerYear: 13500,
    healthInsurancePerMonth: 0,
    englishMasters: "extensive",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 3,
    studentVisaName: "Student residence permit",
    notes:
      "Tuition for non-EEA students was introduced in autumn 2023 and ended Norway's free-for-all reputation; EU/EEA students still pay only the semester fee. Permanent residence is reachable in 3 years.",
  }),
  def({
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    eu: true,
    schengen: true,
    currency: "DKK",
    languages: ["Danish"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(6000, 17000),
    semesterFee: null,
    livingCostPerMonth: r(900, 1450),
    proofOfFundsPerYear: 11000,
    healthInsurancePerMonth: 0,
    englishMasters: "extensive",
    postStudyWorkMonths: 36,
    workHoursPerWeek: 20,
    permanentResidenceYears: 8,
    studentVisaName: "Student residence permit",
    notes:
      "The 3-year establishment card after a Danish master's is the most generous post-study window in Europe, but permanent residence rules are among the strictest.",
  }),
  def({
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Finnish", "Swedish"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(8000, 18000),
    semesterFee: r(35, 70),
    livingCostPerMonth: r(700, 1150),
    proofOfFundsPerYear: 6720,
    healthInsurancePerMonth: 40,
    englishMasters: "extensive",
    postStudyWorkMonths: 24,
    workHoursPerWeek: 30,
    permanentResidenceYears: 4,
    studentVisaName: "Residence permit for studies",
    notes:
      "Non-EU tuition is high on paper but 50–100% scholarships are routine and often automatic on admission. Residence permits are now granted for the full degree duration, and the post-study search window is 2 years.",
  }),
  def({
    code: "IS",
    name: "Iceland",
    flag: "🇮🇸",
    eu: false,
    schengen: true,
    currency: "ISK",
    languages: ["Icelandic"],
    tuitionEu: r(600, 800),
    tuitionNonEu: r(600, 5000),
    semesterFee: null,
    livingCostPerMonth: r(1100, 1700),
    proofOfFundsPerYear: 15600,
    healthInsurancePerMonth: 45,
    englishMasters: "moderate",
    postStudyWorkMonths: 6,
    workHoursPerWeek: 15,
    permanentResidenceYears: 4,
    studentVisaName: "Residence permit for studies",
    notes:
      "Public universities charge only a registration fee regardless of nationality. Very high cost of living and a small, competitive job market.",
  }),
  def({
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    eu: true,
    schengen: false,
    currency: "EUR",
    languages: ["English", "Irish"],
    tuitionEu: r(3000, 9000),
    tuitionNonEu: r(10000, 26000),
    semesterFee: null,
    livingCostPerMonth: r(1050, 1600),
    proofOfFundsPerYear: 10000,
    healthInsurancePerMonth: 50,
    englishMasters: "extensive",
    postStudyWorkMonths: 24,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Stamp 2 study permission",
    notes:
      "English-speaking with a 24-month Third Level Graduate Programme after a master's. Dublin housing costs and scarcity are the dominant risk factor. Not in Schengen.",
  }),
  def({
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    eu: false,
    schengen: false,
    currency: "GBP",
    languages: ["English"],
    tuitionEu: r(17000, 45000),
    tuitionNonEu: r(17000, 45000),
    semesterFee: null,
    livingCostPerMonth: r(1150, 1900),
    proofOfFundsPerYear: 14000,
    healthInsurancePerMonth: 90,
    englishMasters: "extensive",
    postStudyWorkMonths: 18,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Student visa (Tier 4)",
    notes:
      "Post-Brexit there is no EU rate: everyone pays international fees. The Immigration Health Surcharge is payable upfront for the whole visa. Graduate Route gives 18 months (3 years after a PhD).",
  }),
  def({
    code: "PL",
    name: "Poland",
    flag: "🇵🇱",
    eu: true,
    schengen: true,
    currency: "PLN",
    languages: ["Polish"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(2000, 6000),
    semesterFee: null,
    livingCostPerMonth: r(500, 900),
    proofOfFundsPerYear: 5400,
    healthInsurancePerMonth: 15,
    englishMasters: "moderate",
    postStudyWorkMonths: 9,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "National visa D / temporary residence",
    notes:
      "Polish-taught programmes are free for EU nationals and for holders of the Karta Polaka; English-taught degrees carry moderate fees. Students may work without a separate work permit.",
  }),
  def({
    code: "CZ",
    name: "Czechia",
    flag: "🇨🇿",
    eu: true,
    schengen: true,
    currency: "CZK",
    languages: ["Czech"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(0, 15000),
    semesterFee: null,
    livingCostPerMonth: r(550, 950),
    proofOfFundsPerYear: 4600,
    healthInsurancePerMonth: 55,
    englishMasters: "moderate",
    postStudyWorkMonths: 9,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Long-term visa for study",
    notes:
      "Czech-taught degrees are free for every nationality, which is unique in Europe. English-taught programmes charge fees, with medicine at the top of the range.",
  }),
  def({
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Slovak"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(0, 10000),
    semesterFee: null,
    livingCostPerMonth: r(500, 850),
    proofOfFundsPerYear: 4400,
    healthInsurancePerMonth: 40,
    englishMasters: "limited",
    postStudyWorkMonths: 9,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence for study",
    notes: "Slovak-taught study is free for all nationalities; English-taught programmes are fee-paying.",
  }),
  def({
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    eu: true,
    schengen: true,
    currency: "HUF",
    languages: ["Hungarian"],
    tuitionEu: r(0, 3000),
    tuitionNonEu: r(3000, 12000),
    semesterFee: null,
    livingCostPerMonth: r(500, 900),
    proofOfFundsPerYear: 5000,
    healthInsurancePerMonth: 30,
    englishMasters: "moderate",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 30,
    permanentResidenceYears: 5,
    studentVisaName: "Residence permit for study",
    notes:
      "Stipendium Hungaricum is a large, genuinely accessible government scholarship covering tuition plus a stipend for non-EU applicants from partner countries.",
  }),
  def({
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    eu: true,
    schengen: true,
    currency: "RON",
    languages: ["Romanian"],
    tuitionEu: r(500, 1500),
    tuitionNonEu: r(2000, 6000),
    semesterFee: null,
    livingCostPerMonth: r(450, 800),
    proofOfFundsPerYear: 4200,
    healthInsurancePerMonth: 25,
    englishMasters: "limited",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Long-stay visa for studies",
    notes: "Low cost throughout. Medicine in English is the main international draw.",
  }),
  def({
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    eu: true,
    schengen: true,
    currency: "BGN",
    languages: ["Bulgarian"],
    tuitionEu: r(600, 1800),
    tuitionNonEu: r(3000, 8000),
    semesterFee: null,
    livingCostPerMonth: r(400, 750),
    proofOfFundsPerYear: 3600,
    healthInsurancePerMonth: 20,
    englishMasters: "limited",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Type D visa for study",
    notes: "Cheapest cost of living in the EU. Joined Schengen fully in 2025.",
  }),
  def({
    code: "GR",
    name: "Greece",
    flag: "🇬🇷",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Greek"],
    tuitionEu: r(0, 3000),
    tuitionNonEu: r(1500, 9000),
    semesterFee: null,
    livingCostPerMonth: r(550, 950),
    proofOfFundsPerYear: 7200,
    healthInsurancePerMonth: 30,
    englishMasters: "limited",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "National visa type D",
    notes:
      "Undergraduate study in Greek is free. A growing set of English-taught master's programmes charge fees to all students.",
  }),
  def({
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Croatian"],
    tuitionEu: r(0, 1500),
    tuitionNonEu: r(1000, 5000),
    semesterFee: null,
    livingCostPerMonth: r(550, 950),
    proofOfFundsPerYear: 4800,
    healthInsurancePerMonth: 25,
    englishMasters: "limited",
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary stay for study",
    notes: "Adopted the euro and joined Schengen in 2023.",
  }),
  def({
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Slovene"],
    tuitionEu: r(0, 0),
    tuitionNonEu: r(2000, 12000),
    semesterFee: null,
    livingCostPerMonth: r(600, 1000),
    proofOfFundsPerYear: 5400,
    healthInsurancePerMonth: 30,
    englishMasters: "limited",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence for study",
    notes: "Full-time study in Slovene is free for EU nationals; non-EU pay institutional fees.",
  }),
  def({
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Estonian"],
    tuitionEu: r(0, 4000),
    tuitionNonEu: r(1500, 7700),
    semesterFee: null,
    livingCostPerMonth: r(550, 950),
    proofOfFundsPerYear: 4560,
    healthInsurancePerMonth: 30,
    englishMasters: "moderate",
    postStudyWorkMonths: 9,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence permit for study",
    notes:
      "Small but very digital; strong English-taught IT programmes and generous performance-based tuition waivers. Graduates may stay 9 months to job-hunt.",
  }),
  def({
    code: "LV",
    name: "Latvia",
    flag: "🇱🇻",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Latvian"],
    tuitionEu: r(1500, 4000),
    tuitionNonEu: r(2000, 9000),
    semesterFee: null,
    livingCostPerMonth: r(500, 900),
    proofOfFundsPerYear: 6000,
    healthInsurancePerMonth: 25,
    englishMasters: "moderate",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence permit",
    notes: "Moderate fees, low living costs, several English-taught engineering and business degrees.",
  }),
  def({
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Lithuanian"],
    tuitionEu: r(1500, 4000),
    tuitionNonEu: r(2000, 9000),
    semesterFee: null,
    livingCostPerMonth: r(500, 900),
    proofOfFundsPerYear: 5300,
    englishMasters: "moderate",
    healthInsurancePerMonth: 25,
    postStudyWorkMonths: 12,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "National visa D + TRP",
    notes: "State-funded places exist for EU nationals; laser physics and life sciences are notable strengths.",
  }),
  def({
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Luxembourgish", "French", "German"],
    tuitionEu: r(400, 4000),
    tuitionNonEu: r(400, 5000),
    semesterFee: null,
    livingCostPerMonth: r(1200, 1900),
    proofOfFundsPerYear: 16000,
    healthInsurancePerMonth: 30,
    englishMasters: "extensive",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 15,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary authorisation to stay",
    notes:
      "One public university, trilingual, with high salaries and high rents. Strong finance and space-resources niches.",
  }),
  def({
    code: "MT",
    name: "Malta",
    flag: "🇲🇹",
    eu: true,
    schengen: true,
    currency: "EUR",
    languages: ["Maltese", "English"],
    tuitionEu: r(0, 1200),
    tuitionNonEu: r(1000, 13000),
    semesterFee: null,
    livingCostPerMonth: r(800, 1250),
    proofOfFundsPerYear: 8500,
    healthInsurancePerMonth: 35,
    englishMasters: "extensive",
    postStudyWorkMonths: 9,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "National long-stay visa",
    notes: "English is an official language, so instruction is in English by default.",
  }),
  def({
    code: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
    eu: true,
    schengen: false,
    currency: "EUR",
    languages: ["Greek", "English"],
    tuitionEu: r(3500, 7000),
    tuitionNonEu: r(3500, 10000),
    semesterFee: null,
    livingCostPerMonth: r(700, 1150),
    proofOfFundsPerYear: 7200,
    healthInsurancePerMonth: 20,
    englishMasters: "extensive",
    postStudyWorkMonths: 0,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Student temporary residence permit",
    notes:
      "Widely English-taught, but non-EU graduates have very limited rights to stay and work after finishing. Not yet in Schengen.",
  }),
  def({
    code: "RS",
    name: "Serbia",
    flag: "🇷🇸",
    eu: false,
    schengen: false,
    currency: "RSD",
    languages: ["Serbian"],
    tuitionEu: r(1000, 3000),
    tuitionNonEu: r(1000, 3500),
    semesterFee: null,
    livingCostPerMonth: r(400, 750),
    proofOfFundsPerYear: 3600,
    healthInsurancePerMonth: 20,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: 20,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence for study",
    notes: "EU candidate country, outside Schengen. Low cost, mostly Serbian-taught.",
  }),
  def({
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    eu: false,
    schengen: false,
    currency: "UAH",
    languages: ["Ukrainian"],
    tuitionEu: r(1000, 3500),
    tuitionNonEu: r(1000, 4500),
    semesterFee: null,
    livingCostPerMonth: r(350, 700),
    proofOfFundsPerYear: 3000,
    healthInsurancePerMonth: 15,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Type D study visa",
    notes: "Included for completeness. Active conflict — check current advisories before considering.",
  }),
  def({
    code: "AL",
    name: "Albania",
    flag: "🇦🇱",
    eu: false,
    schengen: false,
    currency: "ALL",
    languages: ["Albanian"],
    tuitionEu: r(500, 2500),
    tuitionNonEu: r(500, 3000),
    semesterFee: null,
    livingCostPerMonth: r(350, 650),
    proofOfFundsPerYear: 3000,
    healthInsurancePerMonth: 15,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Type D study visa",
    notes: "EU candidate country. Very low costs, limited English-taught provision.",
  }),
  def({
    code: "BA",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    eu: false,
    schengen: false,
    currency: "BAM",
    languages: ["Bosnian", "Croatian", "Serbian"],
    tuitionEu: r(500, 2500),
    tuitionNonEu: r(500, 3000),
    semesterFee: null,
    livingCostPerMonth: r(350, 650),
    proofOfFundsPerYear: 3000,
    healthInsurancePerMonth: 15,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence for study",
    notes: "EU candidate country, low cost, limited English-taught provision.",
  }),
  def({
    code: "MK",
    name: "North Macedonia",
    flag: "🇲🇰",
    eu: false,
    schengen: false,
    currency: "MKD",
    languages: ["Macedonian"],
    tuitionEu: r(400, 2000),
    tuitionNonEu: r(400, 2500),
    semesterFee: null,
    livingCostPerMonth: r(350, 650),
    proofOfFundsPerYear: 2800,
    healthInsurancePerMonth: 15,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Type D study visa",
    notes: "EU candidate country with the lowest fee levels in the region.",
  }),
  def({
    code: "ME",
    name: "Montenegro",
    flag: "🇲🇪",
    eu: false,
    schengen: false,
    currency: "EUR",
    languages: ["Montenegrin"],
    tuitionEu: r(500, 2500),
    tuitionNonEu: r(500, 3000),
    semesterFee: null,
    livingCostPerMonth: r(400, 700),
    proofOfFundsPerYear: 3000,
    healthInsurancePerMonth: 15,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Temporary residence for study",
    notes: "Uses the euro without being in the eurozone. EU candidate country.",
  }),
  def({
    code: "MD",
    name: "Moldova",
    flag: "🇲🇩",
    eu: false,
    schengen: false,
    currency: "MDL",
    languages: ["Romanian"],
    tuitionEu: r(500, 2500),
    tuitionNonEu: r(500, 3000),
    semesterFee: null,
    livingCostPerMonth: r(300, 600),
    proofOfFundsPerYear: 2600,
    healthInsurancePerMonth: 12,
    englishMasters: "limited",
    postStudyWorkMonths: 0,
    workHoursPerWeek: null,
    permanentResidenceYears: 5,
    studentVisaName: "Type D study visa",
    notes: "EU candidate country, lowest living costs in Europe.",
  }),
  def({
    code: "TR",
    name: "Türkiye",
    flag: "🇹🇷",
    eu: false,
    schengen: false,
    currency: "TRY",
    languages: ["Turkish"],
    tuitionEu: r(300, 1500),
    tuitionNonEu: r(500, 4000),
    semesterFee: null,
    livingCostPerMonth: r(400, 800),
    proofOfFundsPerYear: 3600,
    healthInsurancePerMonth: 20,
    englishMasters: "moderate",
    postStudyWorkMonths: 0,
    workHoursPerWeek: 24,
    permanentResidenceYears: 8,
    studentVisaName: "Student residence permit",
    notes:
      "Only the European side (Istanbul/Thrace) is geographically in Europe. Türkiye Bursları is a large fully-funded scholarship programme.",
  }),
];

export const COUNTRY_BY_CODE: Record<string, CountryProfile> = Object.fromEntries(
  COUNTRY_PROFILES.map((c) => [c.code, c]),
);

/**
 * Drives both the Wikidata import and the country filter. Russia and Belarus
 * are deliberately omitted: add their codes and a profile above to include them.
 */
export const EUROPEAN_COUNTRY_CODES = COUNTRY_PROFILES.map((c) => c.code);

export function getCountry(code: string): CountryProfile | undefined {
  return COUNTRY_BY_CODE[code];
}
